# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'schwablication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for schwablication
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Charts'
  target 'schwablicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'schwablicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
