platform :ios, '11.4'

target 'schwablication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for schwablication

   pod 'Firebase/Auth'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Storage'
   pod 'Charts'

  target 'schwablicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'schwablicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
